server:
  port: 9000
  shutdown: graceful
  forward-headers-strategy: framework
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:msg_db}?ApplicationName=subscriber&sslmode=${DB_SSL_MODE:disable}&prepareThreshold=0
    username: ${DB_USERNAME:msg_user}
    password: ${DB_PASSWORD:777}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: messages
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: messages
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
    show-sql: ${LOGGING_SQL:false}

logging:
  level:
    com.test: info
  file:
    path: logs